services:
  - type: web
    name: fastfood-bot
    runtime: python
    plan: free
    buildCommand: pip install -r fastfood_bot/requirements.txt
    startCommand: python3 fastfood_bot/bot.py
    autoDeploy: true
